// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TODO.Repository.Models;

namespace TODO.Repository.Migrations
{
    [DbContext(typeof(tododbContext))]
    [Migration("20210427050952_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TODO.Repository.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DateStarted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("date_started")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime")
                        .HasColumnName("date_updated");

                    b.Property<DateTime?>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 1",
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 2",
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 3",
                            Status = false
                        },
                        new
                        {
                            Id = 4,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 4",
                            Status = false
                        },
                        new
                        {
                            Id = 5,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 5",
                            Status = false
                        },
                        new
                        {
                            Id = 6,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 6",
                            Status = false
                        },
                        new
                        {
                            Id = 7,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 7",
                            Status = false
                        },
                        new
                        {
                            Id = 8,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 8",
                            Status = false
                        },
                        new
                        {
                            Id = 9,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 9",
                            Status = false
                        },
                        new
                        {
                            Id = 10,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 10",
                            Status = false
                        },
                        new
                        {
                            Id = 11,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 11",
                            Status = false
                        },
                        new
                        {
                            Id = 12,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 12",
                            Status = false
                        },
                        new
                        {
                            Id = 13,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 13",
                            Status = false
                        },
                        new
                        {
                            Id = 14,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 14",
                            Status = false
                        },
                        new
                        {
                            Id = 15,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 15",
                            Status = false
                        },
                        new
                        {
                            Id = 16,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 16",
                            Status = false
                        },
                        new
                        {
                            Id = 17,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 17",
                            Status = false
                        },
                        new
                        {
                            Id = 18,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 18",
                            Status = false
                        },
                        new
                        {
                            Id = 19,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 19",
                            Status = false
                        },
                        new
                        {
                            Id = 20,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 20",
                            Status = false
                        },
                        new
                        {
                            Id = 21,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 21",
                            Status = false
                        },
                        new
                        {
                            Id = 22,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 22",
                            Status = false
                        },
                        new
                        {
                            Id = 23,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 23",
                            Status = false
                        },
                        new
                        {
                            Id = 24,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 24",
                            Status = false
                        },
                        new
                        {
                            Id = 25,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 25",
                            Status = false
                        },
                        new
                        {
                            Id = 26,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 26",
                            Status = false
                        },
                        new
                        {
                            Id = 27,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 27",
                            Status = false
                        },
                        new
                        {
                            Id = 28,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 28",
                            Status = false
                        },
                        new
                        {
                            Id = 29,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 29",
                            Status = false
                        },
                        new
                        {
                            Id = 30,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 30",
                            Status = false
                        },
                        new
                        {
                            Id = 31,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 31",
                            Status = false
                        },
                        new
                        {
                            Id = 32,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 32",
                            Status = false
                        },
                        new
                        {
                            Id = 33,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 33",
                            Status = false
                        },
                        new
                        {
                            Id = 34,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 34",
                            Status = false
                        },
                        new
                        {
                            Id = 35,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 35",
                            Status = false
                        },
                        new
                        {
                            Id = 36,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 36",
                            Status = false
                        },
                        new
                        {
                            Id = 37,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 37",
                            Status = false
                        },
                        new
                        {
                            Id = 38,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 38",
                            Status = false
                        },
                        new
                        {
                            Id = 39,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 39",
                            Status = false
                        },
                        new
                        {
                            Id = 40,
                            Day = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "task 40",
                            Status = false
                        });
                });

            modelBuilder.Entity("TODO.Repository.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
